[workspace]
channels = ["conda-forge"]
name = "DriftwoodMappingBenchmark"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "python ./tools/temp.py"

[dependencies]
cowpy = ">=1.1.5,<2"
python = ">=3.14.0,<3.15"

[pypi-dependencies]
numpy = ">=2.3.4, <3"
